# http port set
server:
  port: 8255

spring:
  # File Size
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  # Oracle Connect
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: S20220102
    password: tiger
    driver-class-name: oracle.jdbc.driver.OracleDriver

  # ORM JPA
#  jpa:
#    hibernate:
#      ddl-auto: none  #  create
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
 
  # gmail Transfer 
  mail:
    host: smtp.gmail.com
    port: 587
    username: ttaekwang3@gmail.com
    password:  
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true  
          
                 
  #view resolver(Templete ->JSP Use)
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp    
 
# Mybatis 
mybatis:
  # dto Location
  # type-aliases-package: com.oracle.oBootMybatis03.model
  # xml Location
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml
      
#logging.level:
#  org.hibernate.SQL: debug
  # org.hibernate.type: trace
  